# -*- coding: utf-8 -*-
"""Projeto avaliação de vinhos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZR5rs4d65YrjjMiqDGgn8BSCq1jk67TH

# **MÓDULO 32 - Exercício**
# Random Forest

Nesta tarefa, vocês vão trabalhar com uma base de dados de avaliações de vinhos, onde o objetivo é prever a pontuação dos vinhos usando o algoritmo de Random Forest para classificação multiclasse.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/winequality-red.csv", delimiter=',')

df.head(10)

"""**Vamos conhecer nossa base:**

Características dos Vinhos (Features)

Fixed Acidity: Acidez fixa do vinho.

Volatile Acidity: Acidez volátil do vinho.

Citric Acid: Quantidade de ácido cítrico no vinho.

Residual Sugar: Açúcar residual presente no vinho.

Chlorides: Nível de cloretos no vinho.

Free Sulfur Dioxide: Dióxido de enxofre livre no vinho.

Total Sulfur Dioxide: Quantidade total de dióxido de enxofre no vinho.

Density: Densidade do vinho.

pH: Nível de pH do vinho.

Sulphates: Quantidade de sulfatos no vinho.

Alcohol: Teor alcoólico do vinho.



**Variável de Saída (Target):**

Quality: Pontuação do vinho baseada em dados sensoriais, variando de 0 a 10.

Esta abordagem permitirá que vocês explorem como diferentes características químicas influenciam a qualidade dos vinhos e como o Random Forest pode ser usado para fazer previsões precisas com base nesses dados.

# 1 - Realize a primeira etapa de pré processamento dos dados.

A) Verifique os tipos de dados.


B) Verifique os dados faltantes, se houver dados faltantes faça a substituição ou remoção justificando sua escolha.
"""

# Verificando os tipos de dados
df.dtypes

# Verificando se a base possui dados faltantes
df.isnull().sum()

"""* Os tipos de dados condizem com suas variaveis, sendo do tipo 'float' para as caracteristicas dos vinhos e do tipo 'int' para a nota final dos vinhos.
* Após a analise inicial não foi detectado dados faltantes na base de dados.

# 2 - Realize a segunda e terceita etapa de pré processamento dos dados.

A) Utilize a função describe para identificarmos outliers e verificarmos a distribuição dos dados.

B) Verifique o balanceamento da váriavel Target.

C)  Plote o gráfico ou a tabela e indique as variáveis que te parecem mais "fortes" na correlação para nosso modelo.

D) Crie um novo dataframe apenas com as váriaveis que parecem ter maior correlação com a target. (Negativa ou positiva)
"""

# Analisando distribuição dos dados
df.describe()

"""* Algumas variaveis apresentam outliers, mas por se tartarem de indices das caracteristicas dos vinhos, optei por nao retira-los
* Apesar de trabalharem em escalas diferentes, as variaveis aparentam estar balanceadas
"""

# Verificando o balanceamento
df['quality'].value_counts()

"""Os dados da variavel target estao bem desbalanceadas, com maior incidencia nas notas 5, 6 e 7. para uma melhor performance do modelo, o ideal seria fazer o balanceamento."""

# Fazendo a correlação dos dados
correlation_matriz = df.corr()
# Plotando a matriz de correlação
plt.figure(figsize=(10,10))
sns.heatmap(correlation_matriz, annot=True, cmap='coolwarm')
plt.title('Matriz de correlação')
plt.show()

"""De acordo com a matriz, em relação a variavel target, as variaveis 'volatile acidity', 'sulphates' e 'alcohol' são as que possuem maiores correlações. Porem eu defini uma regua nas variaveis com correlação maior que 2, seja positivo ou negativo, dando um desconto para a variavel 'total sulfur dioxide'. Creio que as demais variaveis tbm possuem uma correlação notavel para o modelo."""

# Criando uma nova base com as variaveis de maior correlação
base = df.copy()
base.drop(columns=['fixed acidity', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'density', 'pH'], inplace=True)
# Verificando a nova base
base

"""Como explicado anteriormente, criei uma nova base para ser aplicado ao modelo apenas com as variaveis com correlação maior que 2

# 3 - Preparação Final dos Dados

A) Separe a base em X(Features) e Y(Target)

B) Separe a base em treino e teste.
"""

# Separando a base em X e Y
X = base.drop(columns=['quality'], axis=1) # Base sem a variavel target
Y = base['quality'] # Base apenas com a variavel target

# Separando a base de treino e teste
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

"""# 4 - Modelagem

A) Inicie e treine o modelo de Random Forest

B) Aplique a base de teste o modelo.

"""

# Iniciando o modelo Random Forest
winequality_RFmodel = RandomForestClassifier(random_state=42)

# Treinando o modelo
winequality_RFmodel.fit(X_train, Y_train)

Y_pred = winequality_RFmodel.predict(X_test)

"""# 5 - Avaliação

A) Avalie as principais métricas da Claissificação e traga insights acerca do resultado, interprete os valores achados.

B) Você nota que o modelo teve dificuldade para prever alguma classe? Se sim, acredita que tenha relação com o balanceamento dos dados? Explique.

"""

# Avaliando o modelo
accuracy = accuracy_score(Y_test, Y_pred)
report = classification_report(Y_test, Y_pred)
confusion_mat = confusion_matrix(Y_test, Y_pred)

print("Acurácia:", accuracy)
print("Relatório de Classificação:\n", report)
print("Matriz de Confusão:\n", confusion_mat)

"""* O modelo tem uma acuracia de 65%
* As notas 5 e 6 são as que o modelo preve melhor, com f1-score de 0.74 para nota 5 e 0.63 para nota 6
* A nota 7 teve um desempenho moderado com o f1-score de 0.54
* O modelo não conseguiu prever as notas 3, 4 e 8 mostrando que ele nao aprendeu já que possui poucas incidencias com estas notas, possivelmente pelo desbalanceamento dos dados

Devido ao baixo desempenho do modelo, optei por balancear os dados para ver se teremos alguma melhora no desempenho

### Avaliando o modelo com os dados balanceados
"""

# Fazendo o balanceamento dos dados com o SMOTE
smote = SMOTE(random_state=42)
X_train_balanced, Y_train_balanced = smote.fit_resample(X_train, Y_train)

# Iniciando o modelo com os dados balanceados
winequalitybalanced_RFmodel = RandomForestClassifier(random_state=42)

# Treinando o modelo com os dados balanceados
winequalitybalanced_RFmodel.fit(X_train_balanced, Y_train_balanced)

# Fazendo a previsão após o balanceamento dos dados
Y_pred_balanced = winequalitybalanced_RFmodel.predict(X_test)

# Avaliando o modelo após o balanceamento dos dados
accuracy = accuracy_score(Y_test, Y_pred_balanced)
report = classification_report(Y_test, Y_pred_balanced)
confusion_mat = confusion_matrix(Y_test, Y_pred_balanced)

print("Acurácia:", accuracy)
print("Relatório de Classificação:\n", report)
print("Matriz de Confusão:\n", confusion_mat)

"""* O modelo obteve uma acuracia de 57%, um pouco menor em relação ao modelo com os dados desbalanceados
* As notas 5, 6 e 7 continuam sendo as que o modelo qprendeu mais, sendo o f1-score de 0.71 para nota 5, 0.55 para nota 6 e 0.54 para nota 7
* Apesar da melhora em relação ao modelo com os dados desbalanceados, as notas 3, 4 e 8 ainda possuem um desempenho muito baixo

O modelo apresentou uma leve melhora no desempenho com os dados balanceados, porem ainda possui uma baixa generalização dos dados, havendo muita confusão entre as classes.

# 5 - Melhorando os Hyperparametros

A) Defina o Grid de parametros que você quer testar

B) Inicie e Treine um novo modelo utilizando o random search.

C) Avalie os resultados do modelo.

D) Você identificou melhorias no modelo após aplicar o random search? Justifique.


ps. Essa parte da atividade demorará um pouco para rodar!
"""

# Definindo a grid de parametros
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2', None]
}

"""### Aplicando o Random Search no modelo desbalanceado"""

# Configurando o Randomized Search na base desbalanceada
random_search = RandomizedSearchCV(
    estimator=winequality_RFmodel,
    param_distributions=param_grid,
    n_iter=10,
    cv=5,
    verbose=2,
    random_state=42,
    scoring='accuracy'
)

# Executando o Randomized Search na base desbalanceada
random_search.fit(X_train, Y_train)

# Obtendo os melhores parametros para base desbalanceada
best_params = random_search.best_params_
print(f'Melhores parametros: {best_params}')

"""### Aplicando o Random Search no modelo balanceado"""

# Configurando o Randomized Search na base balanceada
random_search_balanced = RandomizedSearchCV(
    estimator=winequalitybalanced_RFmodel,
    param_distributions=param_grid,
    n_iter=10,
    cv=5,
    verbose=2,
    random_state=42,
    scoring='accuracy'
)

# Executando o Randomized Search na base balanceada
random_search_balanced.fit(X_train_balanced, Y_train_balanced)

# Obtendo os melhores parametros para base balanceada
best_params_balanced = random_search_balanced.best_params_
print(f'Melhores parametros: {best_params}')

"""### Treinando o modelo"""

# Treinando o modelo desbalanceado com os melhores hiperparâmetros encontrados acima
winequality_best_rf_model = random_search.best_estimator_
winequality_best_rf_model.fit(X_train, Y_train)

# Fazendo a previsão no modelo desbalanceado
Y_pred_best = winequality_best_rf_model.predict(X_test)

# Treinando o modelo balanceado com os melhores hiperparâmetros encontrados acima
winequality_balanced_best_rf_model = random_search_balanced.best_estimator_
winequality_balanced_best_rf_model.fit(X_train_balanced, Y_train_balanced)

# Fazendo a previsão no modelo balanceado
Y_pred_balanced_best = winequality_balanced_best_rf_model.predict(X_test)

"""### Avaliação dos modelos"""

# Avaliando o modelo desbalanceado
accuracy = accuracy_score(Y_test, Y_pred_best)
report = classification_report(Y_test, Y_pred_best)
conf_matrix = confusion_matrix(Y_test, Y_pred_best)

print(f"Acurácia: {accuracy:.2f}")
print("Relatório de Classificação:\n", report)
print("Matriz de Confusão:\n", conf_matrix)

"""* O modelo teve uma acuracia superior após aplicar os hiperparametros alcançando 67%
* As notas 5 e 6 ainda são as que o modelo teve a  melhor previsão, com f1-score de 0.76 para nota 5 e 0.65 para nota 6
* A nota 7 teve uma redução no desempenho em relação ao modelo sem os ajustes marcando 0.53 no f1-score
* O modelo ainda não conseguiu prever as notas 3, 4 e 8 mostrando que ele ainda nao aprendeu por nao haver muitos exemplos com estas notas
"""

# Avaliando o modelo balanceado
accuracy = accuracy_score(Y_test, Y_pred_balanced_best)
report = classification_report(Y_test, Y_pred_balanced_best)
conf_matrix = confusion_matrix(Y_test, Y_pred_balanced_best)

print(f"Acurácia: {accuracy:.2f}")
print("Relatório de Classificação:\n", report)
print("Matriz de Confusão:\n", conf_matrix)

"""* O modelo obteve uma melhora na acuracia em relação ao modelo sem os ajustes, alcançando 60%
* As notas 5, 6 e 7 continuam sendo as que o modelo qprendeu melhor, já que possuem mais dados de treinamento
* Apesar da melhora em relação ao modelo com sem os ajustes, as notas 3, 4 e 8 ainda possuem um desempenho muito baixo por consequencia da baixa, ou ate mesmo nulas, dos dados para treinamento

Ambos os modelos apresentaram melhoras após os ajustar os hiperparametros, alcaçando indices maiores de pontuação. Mas após avaliar todos os modelos testados, obtive a conclusão de que a falta de dados para treinamento ainda é o fator principal na perda de desempenho dos modelos. Já que, mesmo após o balanceamento dos dados, o modelo obteve um desempenho melhor com os dados desbalanceados

# 6 - Chegando a perfeição

Baseado em tudo que você já aprendeu até agora, quais outras técnicas você acredita que poderiam ser aplicadas ao modelo para melhorar ainda mais suas previsões?

Apesar de ter aplicado o balanceamento nos dados para treinamento como tentativa de melhorar o desempenho do modelo, acredito que, para as notas que tem pouco ou nenhum exemplo, que foi o fator principal para o baixo desempenho do modelo, poderia ser feito um tratamento para normalizar os dados. Por exemplo, como temos um alto numero de dados para as notas 5 e 6, poderia ser feito, alem do SMOTE para as notas com poucos dados, aplicar o Undersampling para reduzir os dados das notas 5 e 6, já que possuem mais dados para treinamento e assim obter uma melhor balanceamento dos dados.
"""